----USADO EN LA BASE DE AMORTIZACIONES

SELECT A.AS_OF_DATE FCH_PROCESO, B.NUMUNICO NO_UNICO, 
       B.ESTATUS ESTATUS_CUENTA, B.REFERENCIA NO_CUENTA, B.PRODSIG COD_PROD, B.DESCPRODSIG PRODUCTO, 
       B.CODEJECUTIVO COD_ASIGNADO, B.CODAREAFIN COD_AREA_FINANCIERA, 
       A.TRANS_AMOUNT MONTO_PAGO, A.ORG_AMOUNT MONTO_REFERENCIA, A.BA_TASAINT TASA_INTERES,
       A.ISO_CURRENCY_CD TIPO_MONEDA, A.BA_MOTIVO MOTIVO, 
	   A.MANTTO TIPO_MOTIVO, A.CONDICION CONDICION
       --SELECT  count(1) --DISTINCT BA_MOTIVO, MANTTO
FROM DWBA.AMORTIZACIONES A JOIN STAGEBA.REFERENCIAS@BASIG B ON A.ID_NUMBER = B.REFERENCIA  
WHERE B.CODAREAFIN IN ('1101','1123','1120','1111','1112','1113','1106','1103') 
AND AS_OF_DATE >= '28/2/20'
--AND EXTRACT(YEAR FROM AS_OF_DATE) >= 2019


------------------------------------------ANTIGUO
------------------------------------------
SELECT A.IDENTITY_CODE FECHA_COD, A.AS_OF_DATE FCH_PROCESO, B.NUMUNICO NO_UNICO, 
       B.ESTATUS ESTATUS_CUENTA, B.REFERENCIA NO_CUENTA, B.PRODSIG COD_PROD, B.DESCPRODSIG PRODUCTO, 
       B.CODEJECUTIVO COD_ASIGNADO, B.CODAREAFIN COD_AREA_FINANCIERA, 
       A.TRANS_AMOUNT MONTO_PAGO, A.ISO_CURRENCY_CD TIPO_MONEDA, A.BA_MOTIVO MOTIVO, 
	   A.MANTTO TIPO_MOTIVO, A.CONDICION CONDICION
       --SELECT  count(1) --DISTINCT BA_MOTIVO, MANTTO
FROM DWBA.AMORTIZACIONES A JOIN STAGEBA.REFERENCIAS@BASIG B ON A.ID_NUMBER = B.REFERENCIA  
WHERE B.CODAREAFIN IN ('1101','1123','1120','1111','1112','1113','1106','1103') 
AND EXTRACT(YEAR FROM AS_OF_DATE) = 2018
AND EXTRACT(MONTH FROM AS_OF_DATE) >= 1 
--AND A.IDENTITY_CODE >= '20180918'
--AND BA_MOTIVO = 'AMORTIZACION'
--AND ROWNUM < 400
--AND IDENTITY_CODE = '20180731'

