    
SELECT B.GRUPOID AS COD_AGRUPADOR_DESTINO, 
       CAST(B.DESCRIPCION AS VARCHAR2(100)) AS DESC_AGRUPADOR_DESTINO, 
       A.FINCODBCR COD_DESTINO_BCR, 
       A.FINDESCDESTINO DESC_DESTINO_BCR, 
       A.FINGRUPORIESGO COD_GRUPO_RIESGO
FROM SIGCATA.SIGCATA_FINCODBCRSSF A LEFT JOIN BACATALOG.CATSECTORBA B
ON A.FINCODSECTORECON = B.GRUPOID
ORDER BY B.GRUPOID, A.FINCODBCR 
;
