--	1. PRIMERO BORRAR LOS CLIENTES NO EMPRESARIAL DE LA BASE
DELETE 
--SELECT COUNT(1)
FROM CLIENTES
WHERE COD_AREA_FIN NOT IN (1103,1106,1113,1112,1111,1120,1123,1101)

--	2. LUEGO VERIFICAR LA �LTIMA FECHA DE ACTUALIZACI�N DEL CAT�LOGO DE CLIENTES PARA ACTUALIZAR 1 MES ADELANTE
SELECT MAX(FECHA_PROCESO) FROM CLIENTES

--	3. LUEGO HACER EL INSERT AL �LTIMO MES ACTUALIZADO DE LA BASE CIFGENERALES
INSERT INTO CLIENTES(FECHA_PROCESO,NO_UNICO,NOMBRE_CLIENTE,COD_ASIGNADO,COD_AREA_FIN,NIT,SEGMENTO_INGRESOS,FCH_INGRESO,CODDOMICILIO,TIPO_CLIENTE)
SELECT FECHA_PROCESO, NO_UNICO, NOMBRE_CLIENTE, COD_ASIGNADO, COD_AREA_FIN, NIT, SEGMENTO_INGRESOS, FCH_INGRESO, CODDOMICILIO, TIPO_CLIENTE
FROM OPENQUERY(SIGBD,'SELECT O985185.CIFFECHAPROCESO AS FECHA_PROCESO, 
							 O985185.CIFCODCLIENTE   AS NO_UNICO, 
							 O985185.CIFNOMBRECLIE   AS NOMBRE_CLIENTE,
							 O985185.CIFCODEJECUTI   AS COD_ASIGNADO, 
							 O985185.CIFCODAREAFIN   AS COD_AREA_FIN, 
							 O985185.CIFNIT			 AS NIT,
							 O985185.CIFSEGMENTO     AS SEGMENTO_INGRESOS,
							 O985185.CIFFECHAINGRE   AS FCH_INGRESO,
							 O985185.CIFPAISDOMICI	 AS CODDOMICILIO,
							 O985185.CIFTIPOCLIENT   AS TIPO_CLIENTE
					  FROM DWBA.CIFGENERALES@BARIESGOS  O985185
					  WHERE  ( EXTRACT(YEAR  FROM O985185.CIFFECHAPROCESO) = 2020)
							 AND   ( EXTRACT(MONTH FROM O985185.CIFFECHAPROCESO) = 05)')


----- 4. ACTUALIZAR LOS NOMBRES DE LAS �REAS FINANCIERAS
UPDATE A 
SET A.AREA_FIN = B.AREA_FINANCIERA
FROM CLIENTES A JOIN CATALOGO_AREAS_FINANCIERAS B 
	 ON A.COD_AREA_FIN = B.COD_AREA_FINANCIERA
WHERE A.FECHA_PROCESO = (SELECT MAX(FECHA_PROCESO) FROM CLIENTES) 


UPDATE A 
SET A.MASTER = B.NO_UNICO_GRUPO,
	A.NOMBRE_GRUPO = B.NOMBRE_GRUPO,
	A.TIPO_GRUPO = B.TIPO_GRUPO
FROM CLIENTES A JOIN GRUPOS_ECONOMICOS B 
	 ON A.NO_UNICO = B.NO_UNICO_CLIENTE
WHERE A.FECHA_PROCESO = (SELECT MAX(FECHA_PROCESO) FROM CLIENTES) 

UPDATE CLIENTES
SET TIPO_GRUPO = 'Individual'
WHERE TIPO_GRUPO IS NULL
AND FECHA_PROCESO = (SELECT MAX(FECHA_PROCESO) FROM CLIENTES)

UPDATE CLIENTES
SET NIT = RTRIM(LTRIM(NIT)),
	NOMBRE_CLIENTE = RTRIM(LTRIM(NOMBRE_CLIENTE)),
	NOMBRE_GRUPO = RTRIM(LTRIM(NOMBRE_GRUPO))
WHERE FECHA_PROCESO = (SELECT MAX(FECHA_PROCESO) FROM CLIENTES)
