

TRUNCATE TABLE BASE_SALDOS_SSF

--INSERTANDO LOS DATOS NUEVAMENTE A LA TABLA BASE DE SALDOS_SSF
INSERT INTO BASE_SALDOS_SSF
SELECT DISTINCT A.FECHA_CORTE, MONTH(A.FECHA_CORTE) MES, A.NIT, NULL TIPO_CONTRIBUYENTE, A.TIPO_PERSONA, 
	   NULL CLIENTE_BA, 
	   NULL NOMBRE_CLIENTE, 
	   NULL NO_UNICO, 
	   NULL NOMBRE_GRUPO, 
	   NULL NO_MASTER, 
	   NULL AREA_FINANCIERA, 
	   NULL COD_AREA_FIN, 
	   NULL SEGMENTO_BANCA, 
	   NULL COD_ASIGNADO,
	   A.INSTITUCION, A.CODIGO, A.TIPO_INSTITUCION, A.ROL, A.SALDO_ADEUDADO, NULL SALDO_ADEUDADO_BA
FROM SALDOS_CLIENTES_SSF A
UNION 
SELECT DISTINCT A.FECHA_CORTE, MONTH(A.FECHA_CORTE) MES, A.NIT, NULL TIPO_CONTRIBUYENTE, NULL TIPO_PERSONA, 
	   NULL CLIENTE_BA, 
	   NULL NOMBRE_CLIENTE, 
	   NULL NO_UNICO, 
	   NULL NOMBRE_GRUPO, 
	   NULL NO_MASTER, 
	   NULL AREA_FINANCIERA, 
	   NULL COD_AREA_FIN, 
	   NULL SEGMENTO_BANCA, 
	   NULL COD_ASIGNADO,
	   A.INSTITUCION, A.CODIGO, A.TIPO_INSTITUCION, A.ROL, A.SALDO_ADEUDADO, NULL SALDO_ADEUDADO_BA
FROM SALDOS_COMPLETOS_CONVERT A
ORDER BY A.FECHA_CORTE, A.NIT, A.TIPO_INSTITUCION, A.SALDO_ADEUDADO 


--ACTUALIZANDO FLAG CLIENTE_BA

UPDATE A
SET	 A.CLIENTE_BA = CASE WHEN B.NIT IS NULL THEN 'NO CLIENTE BA' ELSE 'CLIENTE BA' END,
	 A.NOMBRE_CLIENTE = B.NOMBRE_CLIENTE,
	 A.NO_UNICO		  = B.NO_UNICO,
	 A.NOMBRE_GRUPO	  = B.NOMBRE_GRUPO, 
	 A.NO_MASTER	  = B.MASTER,
	 A.AREA_FINANCIERA= B.AREA_FIN,
	 A.COD_AREA_FIN	  = B.COD_AREA_FIN,
	 A.COD_ASIGNADO	  = B.COD_ASIGNADO
FROM BASE_SALDOS_SSF A LEFT JOIN VW_CLIENTES_ULT_MES B 
ON A.NIT = B.NIT 

---ACTUALIZANDO EL SEGMENTO DE LA BANCA 
UPDATE BASE_SALDOS_SSF
SET SEGMENTO_BANCA = CASE WHEN COD_AREA_FIN IN (1101,1103,1106,1113,1112,1111,1120,1123) 
					 THEN 'BANCA EMPRESAS' ELSE 'OTRO' END 

---ACTUALIZANDO FLAG DE TIPO CONTRIBUYENTE (ALTO, MEDIANO Y SIN INFO)
UPDATE A 
SET	   A.TIPO_CONTRIBUYENTE = CASE WHEN B.TIPO_CONTRIBUYENTE IS NULL 
							  THEN 'SIN INFO' ELSE B.TIPO_CONTRIBUYENTE END
FROM BASE_SALDOS_SSF A LEFT JOIN BASE_CONTRIBUYENTES B
ON A.NIT = B.NIT

---ASIGNANDOLE VALOR NULL A NOMBRE QUE ESTÁN COMO 'NULL' DESDE LA BASE DE EXCEL
UPDATE SALDOS_CLIENTES_SSF
SET NOMBRE_SOCIEDAD = NULL 
WHERE NOMBRE_SOCIEDAD = 'NULL'

--ASIGNANDO EL NOMBRE DE CLIENTE PARA AQUELLOS QUE NO ESTÁN DENTRO DE LA BASE (NO CLIENTES COMO TAL)
UPDATE A
SET A.NOMBRE_CLIENTE = CASE WHEN B.NOMBRE_SOCIEDAD IS NOT NULL THEN B.NOMBRE_SOCIEDAD
					   ELSE B.PRIMER_NOMBRE+' '+ B.SEGUNDO_NOMBRE+' '+ B.PRIMER_APELLIDO+' '+ B.SEGUNDO_APELLIDO END
FROM BASE_SALDOS_SSF A JOIN SALDOS_CLIENTES_SSF B 
ON A.NIT = B.NIT
WHERE A.NOMBRE_CLIENTE IS NULL 

--SI NO TIENEN NOMBRE EN LA BASE CONSULTA LA DE MEDIANOS Y GRANDES CONTRIBUYENTES
UPDATE A
SET A.NOMBRE_CLIENTE = B.NOMBRE_CONTRIBUYENTE
FROM BASE_SALDOS_SSF A JOIN BASE_CONTRIBUYENTES B ON A.NIT = B.NIT
WHERE A.NOMBRE_CLIENTE IS NULL 

--PARA ACTUALIZAR LA COLUMNA DE SALDO_ADEUDADO_BA
UPDATE A
SET A.SALDO_ADEUDADO_BA = B.SALDO_BA
FROM BASE_SALDOS_SSF A LEFT JOIN (SELECT B.FECHA_CORTE, B.NIT, SUM(SALDO_ADEUDADO) SALDO_BA
								  FROM BASE_SALDOS_SSF B
								  WHERE B.CODIGO = 'BC03' AND B.ROL = 'Deudor'
								  GROUP BY B.FECHA_CORTE, B.NIT) B
ON A.FECHA_CORTE = B.FECHA_CORTE AND A.NIT = B.NIT 


--select top 40 * 
--from BASE_SALDOS_SSF
--where SALDO_ADEUDADO_BA is not null
