SELECT COLFCHPROC AS FECHA_PROCESO, COLREFEREN AS REFERENCIA, COLFEAPE AS FECHA_APERTURA, COLFEVEN AS FECHA_VENCIMIENTO, 
       COLSALDO AS SALDO, COLMONTO AS MONTO, 
CASE  WHEN FGMCOB = '01' THEN 'ADUANAL' WHEN FGMCOB = '02' THEN 'LICENCIA JUVENIL' 
    WHEN FGMCOB = '03' THEN 'OFERTA' WHEN FGMCOB = '04' THEN 'ENERGIA ELECTRICA'
    WHEN FGMCOB = '05' THEN 'VICIOS OCULTOS' WHEN FGMCOB = '06' THEN 'FIEL CUMPLIMIENTO' 
    WHEN FGMCOB = '07' THEN 'INSTITUCIONES FINANCIERAS' WHEN FGMCOB = '08' THEN 'CASAS TRAMITADORAS' 
    WHEN FGMCOB = '09' THEN 'MEDIOS PUBLICITARIOS' WHEN FGMCOB = '10' THEN 'JUEZ EJECUTOR' 
    WHEN FGMCOB = '11' THEN 'ANTICIPO' WHEN FGMCOB = '12' THEN 'BUENA CALIDAD/BUENA OBRA' 
    WHEN FGMCOB = '13' THEN 'ENERGIA ELECTRICA' WHEN FGMCOB = '14' THEN 'PAGO DE IMPUESTOS' 
    WHEN FGMCOB = '15' THEN 'JUICIOS' WHEN FGMCOB = '16' THEN 'AMBIENTAL' 
    WHEN FGMCOB = '17' THEN 'PAGO A TERCEROS' ELSE 'NO SE ENCONTRO' END TIPO_FIANZA, 
FGMCMO AS COMISION_ORIGINAL, FGMCMS AS COMISION_DIFEREIDA, LTRIM(RTRIM(FGMGLN)) AS CUENTA_CONTABLE, LTRIM(RTRIM(FGMGT1)) AS DESCRIPCION_DE_LA_GARANTIA,
LTRIM(RTRIM(FGMBEN)) AS BENEFICIARIO
FROM STAGEBA.FGMST_STAGE@BASIG A INNER JOIN DWBA.COLDOCUM@BASIG B 
ON (A.FGMACC = B.COLREFEREN)
AND COLSALDO > 0
ORDER BY FGMCOB 
