--BORRAR TODOS LOS DATOS
TRUNCATE TABLE GRUPOS_ECONOMICOS


--DECLARACIÓN DE TABLA TEMPORAL PARA DESCARGAR EN ELLA TODOS LOS GRUPOS ECONÓMICOS--
DECLARE @GRUPOS_TEMP TABLE (
	NO_UNICO VARCHAR(25),
	MASTER	 VARCHAR(25),
	NOMBRE_GRUPO VARCHAR(MAX),
	TIPO_GRUPO VARCHAR(25),
	COD_EJECUTIVO VARCHAR(25));

INSERT INTO @GRUPOS_TEMP
	SELECT  NO_UNICO, MASTER, NOMBRE_GRUPO, TIPO_GRUPO, COD_EJECUTIVO--select *
	FROM OPENQUERY(SIGBD,'SELECT C.BK_CLIENTE NO_UNICO, C.BK_MASTER MASTER, C.BD_MASTER NOMBRE_GRUPO,
						  BK_RELACION_COMERCIAL TIPO_GRUPO, C.BK_EJECUTIVO COD_EJECUTIVO
						  FROM DMDIMENSIONES.D_CLIENTE@BASIG C 
						  WHERE BK_RELACION_COMERCIAL not in (''I'') ')

--C.BK_AREA_FINANCIERA IN (1101,1123,1120,1111,1112,1113,1106,1103) AND						  
--SELECT  FINCODCLIENTE, FINCODMASTER, FINNOMBREGRUPO, FINTIPOGRUPO, FINCODEJECUTIVO
--from openquery(sigbd,'SELECT O1128130.FINCODCLIENTE, O1128130.FINCODMASTER, 
--							 O1128160.FINNOMBREGRUPO, O1128130.FINTIPOGRUPO, O1128160.FINCODEJECUTIVO
--					  FROM STAGEBA.FINCLIENTEGRUPO O1128130, BACATALOG.CATGRUPOECONOMICO@BASIG O1128160
--					  WHERE (O1128160.FINCODGRUPOECONOMICO = O1128130.FINCODMASTER )')


--INSERTA EN LA TABLA DE GRUPOS  ECONÓMICOS (FIJA) AQUELLOS GRUPOS QUE NO HAYAN ESTADO DESDE ANTES--

--SELECT * FROM @GRUPOS_TEMP
INSERT INTO GRUPOS_ECONOMICOS
SELECT * FROM @GRUPOS_TEMP
WHERE (MASTER NOT IN (select distinct NO_UNICO_GRUPO from GRUPOS_ECONOMICOS) 
	   OR NO_UNICO NOT IN (select distinct NO_UNICO_CLIENTE
							from GRUPOS_ECONOMICOS))
