SELECT A.AS_OF_DATE, B.BD_VICEPRECIDENTE, 
B.BK_AREA_FINANCIERA, B.BD_AREA_FINANCIERA, B.BK_EJECUTIVO, B.BD_EJECUTIVO,
CASE WHEN B.BK_EJECUTIVO IN ('24','19','10','698','679','619','199','116','111','508','507',
                             '506','505','502','913','95','94','92') THEN 'NO GERENCIADO'
                             ELSE 'GERENCIADO' END GERENCIAMIENTO,
B.BK_MASTER, B.BD_MASTER, A.NO_UNICO,B.BD_CLIENTE, A.AGRUPADOR, C.COLAGRUPAPROD, 
CASE WHEN A.PRODUCT_ID = '60500' THEN 'PLANILLA'
		      WHEN A.PRODUCT_ID = '90301' THEN 'ADQUIRENCIA'
              WHEN A.PRODUCT_ID = '90936' THEN 'FORWARD'
              WHEN A.PRODUCT_ID = '90011' THEN 'BOLETA DE PAGO'
			  WHEN A.PRODUCT_ID = '99061' THEN 'PLANILLA'
			  WHEN A.PRODUCT_ID = '99071' THEN 'CAJA OUTSOURCING' ELSE C.COLAGRUPAPROD END AGUPADOR_VAL,
A.PRODUCT_ID, A.PRODUCT_DES, A.REFERENCIA 
FROM STAGEBA.CLIENTES_IVC@BASIG A JOIN DMDIMENSIONES.D_CLIENTE@BASIG B 
ON A.NO_UNICO = B.BK_CLIENTE LEFT OUTER JOIN BACATALOG.CATPRODUCTOS C
ON A.PRODUCT_ID = C.COLCODPRODUCTO
WHERE A.AS_OF_DATE >= '01/01/19'
AND BK_VICEPRECIDENTE = '1' 
--B.BK_AREA_FINANCIERA = '1123'
--AND A.AS_OF_DATE = '30/09/19'
;