SELECT A.AS_OF_DATE FCH_PROCESO, CAST(C.BK_AREA_FINANCIERA AS NUMBER)COD_AREA_FINANCIERA, 
       CAST(C.BK_EJECUTIVO AS NUMBER) COD_ASIGNADO, 
	     A.NO_UNICO,  
		 CASE WHEN A.PRODUCT_ID = '60500' THEN 'PLANILLA'
		      WHEN A.PRODUCT_ID = '90301' THEN 'ADQUIRENCIA'
                  WHEN A.PRODUCT_ID = '90936' THEN 'FORWARD'
                  WHEN A.PRODUCT_ID = '90011' THEN 'BOLETA DE PAGO'
			WHEN A.PRODUCT_ID = '99061' THEN 'PLANILLA'
			WHEN A.PRODUCT_ID = '99071' THEN 'CAJA OUTSOURCING'
			WHEN A.AGRUPADOR  = 'OTRAS PRODUCTOS' THEN  D.COLAGRUPAPROD ELSE A.AGRUPADOR END AS AGRUPADOR,		 
		   --D.COLAGRUPAPROD AGRUPADOR, 
       A.PRODUCT_ID, A.PRODUCT_DES NOMBRE_PRODUCTO, 	--A.AGRUPADOR TABLA_IVC,
       A.REFERENCIA	
FROM STAGEBA.CLIENTES_IVC@BASIG A JOIN DMDIMENSIONES.D_CLIENTE@BASIG C ON A.NO_UNICO = C.SK_CLIENTE
JOIN BACATALOG.CATPRODUCTOS D ON A.PRODUCT_ID = D.COLCODPRODUCTO
WHERE BK_VICEPRECIDENTE IN ('1','3','ND','4') AND A.NO_UNICO > 0
AND A.AS_OF_DATE = '30/09/20'
UNION ALL
SELECT  A.FCH_PROCESO, A.COD_AREA_FINANCIERA, A.COD_ASIGNADO, A.NO_UNICO,
        --A.SEGMENT1, 
        CASE WHEN A.COD_PRODUCTO IN ('12496','12497') THEN 'LEASING' 
        --   WHEN A.COD_PRODUCTO IN ('90400') THEN 'FIANZAS' --NO TOMAR EN CUENTA 
        --   WHEN A.COD_PRODUCTO IN ('90601','90611') THEN 'CARTA CREDITO' --NO TOMAR YA EN CUENTA
        --   WHEN A.COD_PRODUCTO IN ('90710') THEN 'CARTA CREDITO' --NO TOMAR EN CUENTA
             END AS AGRUPACION,
        --'LEASING' AGRUPACION,
        A.COD_PRODUCTO, A.PRODUCTO, NO_CUENTA   
        ---,A.SALDO, A.MONTO        
FROM DASHBA.DASH_PORTAFOLIO_HIST@BASIG A
WHERE ( A.SEGMENT1 IN ('014.LEASING') ) 
      --'4. FIANZAS Y AVALES','7. CARTAS DE CREDITO','4. FIANZAS' ESTOS PRODUCTOS YA VIENEN EN LA TABLA DE CLIENTES_IVC
      AND (A.FCH_PROCESO IN (TO_DATE('2020093000000','YYYYMMDDHH24MISS'))) --,TO_DATE('2019022800000','YYYYMMDDHH24MISS')))
      AND ( A.STATUS != 'S')
ORDER BY FCH_PROCESO ASC      
;

/**************
AJUSTES A PRODUCTOS DEBIDO AL CRUCE CON CATÁLOGO DE PRODUCTOS DE RENTABILIDAD:
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'DIFERENCIAL CAMBIARIO' WHERE PRODUCT_ID = '11515'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'ACH' WHERE PRODUCT_ID = '90057'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'GARANTIAS' WHERE PRODUCT_ID = '90710'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'SERVICIO A DOMICILIO' WHERE PRODUCT_ID = '90750'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'FIDEICOMISOS' WHERE PRODUCT_ID = '90800'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'FIDEICOMISOS' WHERE PRODUCT_ID = '90801'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'FONDOS INVERSION' WHERE PRODUCT_ID = '90827'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'TRANSFERENCIAS CABLEGRÁFICAS' WHERE PRODUCT_ID = '90902'
UPDATE BASE_OTROS_PRODUCTOS SET AGRUPADOR = 'SEGUROS' WHERE PRODUCT_ID = '99004'
**************/
