SELECT  A.FCH_PROCESO, a.NO_UNICO, A.COD_AREA_FINANCIERA,
        A.SEGMENT1, SEGMENT2 ,NO_CUENTA, A.COD_PRODUCTO,  
        CASE WHEN A.COD_PRODUCTO IN ('12496','12497') THEN 'LEASING' 
             WHEN A.COD_PRODUCTO IN ('90400') THEN 'FIANZAS' 
             WHEN A.COD_PRODUCTO IN ('90601','90611') THEN 'CARTA CREDITO' 
             WHEN A.COD_PRODUCTO IN ('90710') THEN 'CARTA CREDITO' END AS AGRUPACION        
        ,A.SALDO, A.MONTO        
--SELECT A.FCH_PROCESO FECHA, A.COD_PRODUCTO PROD_COA_ID, A.SEGMENT1 AGRUPA_PRODUCTO, A.COD_AREA_FINANCIERA ORG_UNIT_ID, 
  --A.NO_UNICO CUST_NO, A.NO_CUENTA ID_NUMBER, A.SALDO SALDO_PROMEDIO, A.MONTO MONTO
FROM DASHBA.DASH_PORTAFOLIO_HIST@BASIG A
WHERE ( A.SEGMENT1 IN ('4. FIANZAS Y AVALES','7. CARTAS DE CREDITO','4. FIANZAS','014.LEASING') ) 
      --AND ( A.FCH_PROCESO >= TO_DATE('20181105000000','YYYYMMDDHH24MISS') )
      AND (A.FCH_PROCESO IN (SELECT MAX(A.FCH_PROCESO) FCH_PROCESO FROM DASHBA.DASH_PORTAFOLIO_HIST@BASIG A
                             WHERE  A.FCH_PROCESO >= TO_DATE('20190430000000','YYYYMMDDHH24MISS') 
                             --EXTRACT(YEAR FROM A.FCH_PROCESO) >= 2018 AND EXTRACT(MONTH FROM A.FCH_PROCESO) >= 5
                             GROUP BY EXTRACT(YEAR FROM A.FCH_PROCESO), EXTRACT(MONTH FROM A.FCH_PROCESO)))
      AND ( A.STATUS != 'S')
        --AND ( A.COD_AREA_FINANCIERA IN (1103,1106,1113,1112,1111,1120,1123,1101));
