    
    
    select A.FCH_PROC, A.TRAVDM MES, A.TRAVDD DIA, A.TRABTH LOTE_PORTAL, A.TRAACC NO_CUENTA,
    TRACDE NMONICO_PORTAL, TRANEM TIPO_TRX, TRAAMT MONTO_TRX,  --max(fch_proc)
     B.ESTATUS, B.FECHA_CREACION, B.PRODSIG, B.DESCPRODSIG, B.NUMUNICO, C.BD_CLIENTE, 
     BK_AREA_FINANCIERA, BD_AREA_FINANCIERA, BK_EJECUTIVO, BD_EJECUTIVO
    FROM DWBA.TTRAN_HIST@BASIG A 
    JOIN STAGEBA.REFERENCIAS@BASIG B ON A.TRAACC = B.REFERENCIA
    JOIN DMDIMENSIONES.D_CLIENTE@BASIG C ON B.NUMUNICO = C.SK_CLIENTE 
    WHERE --A.TRAACC = '5010421232'
    --and TRABDY = 2019 and TRABDM = 2 --and 
    fch_proc >= '01/01/19'
    and fch_proc <= '31/12/19'
    --and TRAAMT > 400 and TRAAMT < 500
    AND TRACDE = 'DB'
    and tranem = 'PBOL' and A.TRABTH = '1433'
    order by fch_proc;
    