

SELECT TOP 10 * --DISTINCT CASE WHEN A.NOMBRE_SOCIEDAD IS NULL 
			--THEN A.PRIMER_NOMBRE+' '+A.SEGUNDO_NOMBRE+' '+A.PRIMER_APELLIDO+' '+A.SEGUNDO_APELLIDO 
			--ELSE A.NOMBRE_SOCIEDAD END NOMBRE
FROM SALDOS_CLIENTES_SSF A


SELECT INSTITUCION, TIPO_INSTITUCION, --NIT, 
			[ENERO],[FEBRERO],[MARZO],[ABRIL],[MAYO],[JUNIO],[JULIO],[AGOSTO] --SELECT DISTINCT MES
,FEBRERO-ENERO DIF
FROM (
	SELECT INSTITUCION, TIPO_INSTITUCION, --NIT, 
			MES, SALDO_ADEUDADO
	FROM SALDOS_CLIENTES_SSF WHERE  AÑO = 2016
	AND ROL = 'DEUDOR' ) AS ST
	PIVOT (
		SUM(SALDO_ADEUDADO)
		FOR MES IN ([ENERO],[FEBRERO],[MARZO],[ABRIL],[MAYO],[JUNIO],[JULIO],[AGOSTO]) 
	) AS PT 
ORDER BY INSTITUCION --NIT, 

--[ENERO],[FEBRERO],[MARZO],[ABRIL],[MAYO],[JUNIO],[JULIO],[AGOSTO]


SELECT FCH_PROCESO, NO_UNICO, 'SALDOS',--NIT, 
			[PORTAFOLIO DEPOSITOS],[1. PORTAFOLIO PRESTAMOS] --SELECT DISTINCT MES
FROM (
	SELECT FCH_PROCESO, NO_UNICO, SALDO_CONTABLE, SEGMENT1	--SELECT TOP 10 *
	FROM SALDOS_BEG
	WHERE  YEAR(FCH_PROCESO) = 2016
	AND COD_AREA_FINANCIERA = 1113
	AND FCH_PROCESO IN (SELECT MAX(FCH_PROCESO) FROM SALDOS_BEG GROUP BY MONTH(FCH_PROCESO))
	) AS ST
	PIVOT (
		SUM(SALDO_CONTABLE)
		FOR SEGMENT1 IN ([PORTAFOLIO DEPOSITOS],[1. PORTAFOLIO PRESTAMOS]) 
	) AS PT 
UNION 
SELECT FCH_PROCESO, NO_UNICO, 'No PRODUCTOS',--NIT, 
			[PORTAFOLIO DEPOSITOS],[1. PORTAFOLIO PRESTAMOS] --SELECT DISTINCT MES
FROM (
	SELECT FCH_PROCESO, NO_UNICO, NO_CUENTA, SEGMENT1	--SELECT TOP 10 *
	FROM SALDOS_BEG
	WHERE  YEAR(FCH_PROCESO) = 2016
	AND COD_AREA_FINANCIERA = 1113
	AND FCH_PROCESO IN (SELECT MAX(FCH_PROCESO) FROM SALDOS_BEG GROUP BY MONTH(FCH_PROCESO))
	) AS ST
	PIVOT (
		COUNT(NO_CUENTA)
		FOR SEGMENT1 IN ([PORTAFOLIO DEPOSITOS],[1. PORTAFOLIO PRESTAMOS]) 
	) AS PT 

ORDER BY FCH_PROCESO, NO_UNICO 